### PR TITLE
README: Add AUR package instructions

### LINKED ISSUE #77: Package kbs2 for AUR-based distributions
This should be relatively simpler with [`cargo aur`](https://github.com/fosskers/cargo-aur).

### PR DESCRIPTION
**Pull request by orhun**
Hey,
I'm an [Arch Linux](https://aur.archlinux.org) package [maintainer](https://github.com/orhun/PKGBUILDs). I'm submitting this PR to let you know that I created the following packages for the installation of `kbs2` on Arch Linux and other distributions that support installing packages from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository):

* [kbs2](https://aur.archlinux.org/packages/kbs2/) (builds from source)
* [kbs2-git](https://aur.archlinux.org/packages/kbs2-git/) (VCS/development package)

I also updated README.md about installation from AUR. (b943689) (resolves #77)

PS: I can also create a `-bin` package if you provide a pre-compiled x86_64 binary along with the release artifacts.

BR,
orhun.

### CODE REVIEW

**Comment by woodruffw** [comment]
This is fantastic, thank you! I can see about adding some pre-compiled x86_64 binaries to the tagged GitHub releases via the CI, similarly to how Debian packages are currently built.

**Comment by orhun** [comment]
You might want to check [this](https://github.com/orhun/kmon/blob/master/.github/workflows/cd.yml#L30) out. I don't know if it fits your current CD but the abstract is there. Also it'd be awesome if you provide (SHA or MDA) checksums with the binary.

**Comment by woodruffw** [comment]
Thanks for the reference. Yeah, something close to that should mesh well with the current setup. I'll look at doing it tonight (EST).

**Comment by woodruffw** [comment]
Okay, I've gone ahead and done the relevant CI/CD plumbing. `v0.1.6` will be the first non-rc release to have a tarball and SHA2-256 attached to its release.

I'll go ahead and merge this now, feel free to open a follow-up PR if anything needs to be changed!

**Comment by orhun** [comment]
Alright, here's the `-bin` package: https://aur.archlinux.org/packages/kbs2-bin/

**Comment by woodruffw** [comment]
Awesome, thanks for taking the time to package everything!

**Pull request merged**
